# Generated by Django 5.0.7 on 2025-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('price_including_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_excluding_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.CharField(max_length=100)),
                ('num_reviews', models.IntegerField(default=0)),
                ('rating', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('page_url', models.URLField(unique=True)),
                ('crawl_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
